#![expect(
    clippy::string_slice,
    reason = "tests verify exact generated byte ranges"
)]
#![expect(
    clippy::disallowed_types,
    reason = "tests prove immutable leaves remain shared"
)]

use std::path::{Path, PathBuf};
use vize_carton::FxHashMap;

use super::scaling_tests::open;
use crate::corsa_bridge::{CorsaMaterializedSource, EditorMirrorSession};

fn mapped_label(source: &CorsaMaterializedSource) {
    let offset = source.source.rfind("label").unwrap();
    let before_rewrite = source
        .mapping
        .spans()
        .iter()
        .flat_map(|span| {
            std::iter::once((&span.src_range, &span.gen_range)).chain(
                span.sub_spans
                    .iter()
                    .map(|sub| (&sub.src_range, &sub.gen_range)),
            )
        })
        .filter(|(range, _)| range.contains(&offset))
        .min_by_key(|(range, _)| range.len())
        .map_or(offset, |(range, generated)| {
            generated.start + offset - range.start
        });
    let generated = source
        .import_source_map
        .get_virtual_offset(before_rewrite as u32) as usize;
    assert_eq!(&source.code[generated..generated + 5], "label");
}

fn request(context: &super::super::PreparedAliasContext, path: &Path) -> PathBuf {
    context
        .mirror
        .as_ref()
        .unwrap()
        .preferred_materialized_path_for_original(path)
        .unwrap()
}

#[test]
fn unrelated_hosts_share_immutable_maps_without_joining_each_others_closure() {
    let root = tempfile::tempdir().unwrap();
    let root = root.path().canonicalize().unwrap();
    std::fs::write(root.join("tsconfig.json"), "{\"include\":[\"**/*\"]}").unwrap();
    let model = root.join("model.ts");
    std::fs::write(&model, "export const model = { label: 'model' }; ").unwrap();
    let a = root.join("A.tsx");
    let b = root.join("B.jsx");
    let a_source = "import { model } from './model'; const mark = 'é'; export const A = () => <div>{model.label}</div>;";
    let b_source = "import { model } from './model'; const mark = '日本語'; export const B = () => <span>{model.label}</span>;";
    std::fs::write(&a, a_source).unwrap();
    std::fs::write(&b, b_source).unwrap();
    let overlays = FxHashMap::from_iter([(a.clone(), a_source), (b.clone(), b_source)]);
    let session = EditorMirrorSession::new();
    let first = open(&session, &a, a_source, &overlays);
    let second = open(&session, &b, b_source, &overlays);
    let a_request = request(&first, &a);
    let b_request = request(&second, &b);
    assert!(
        first
            .source_catalog
            .shares_revision_with(&second.source_catalog)
    );
    assert!(
        !first
            .mirror
            .as_ref()
            .unwrap()
            .registered_original_paths_sorted()
            .contains(&b)
    );
    assert!(
        !second
            .mirror
            .as_ref()
            .unwrap()
            .registered_original_paths_sorted()
            .contains(&a)
    );
    for (path, authored) in [(&a_request, a_source), (&b_request, b_source)] {
        let source = first.source_catalog.get(path).unwrap();
        assert_eq!(source.source.as_str(), authored);
        mapped_label(&source);
    }
    let edited = b_source.replace("日本語", "different 🦀 prefix");
    let edited_overlays =
        FxHashMap::from_iter([(a.clone(), a_source), (b.clone(), edited.as_str())]);
    let third = open(&session, &a, a_source, &edited_overlays);
    assert!(
        !first
            .source_catalog
            .shares_revision_with(&third.source_catalog)
    );
    let old_b = first.source_catalog.get(&b_request).unwrap();
    let new_b = third.source_catalog.get(&b_request).unwrap();
    assert_eq!(old_b.source.as_str(), b_source);
    assert_eq!(new_b.source.as_str(), edited);
    mapped_label(&old_b);
    mapped_label(&new_b);
    let closed_overlays = FxHashMap::from_iter([(a.clone(), a_source)]);
    let closed = open(&session, &a, a_source, &closed_overlays);
    assert!(closed.source_catalog.get(&b_request).is_none());
    assert_eq!(
        first
            .source_catalog
            .get(&b_request)
            .unwrap()
            .source
            .as_str(),
        b_source
    );
    assert_eq!(
        third
            .source_catalog
            .get(&b_request)
            .unwrap()
            .source
            .as_str(),
        edited
    );
    std::fs::write(&model, "export const model = { label: 'saved' }; ").unwrap();
    let saved = open(&session, &a, a_source, &closed_overlays);
    assert!(
        !closed
            .source_catalog
            .shares_revision_with(&saved.source_catalog)
    );
    let model_request = request(&saved, &model);
    assert!(
        saved
            .source_catalog
            .get(&model_request)
            .unwrap()
            .code
            .contains("'saved'")
    );
}

#[test]
fn authored_host_edits_without_overlays_fork_only_the_changed_query_facts() {
    let root = tempfile::tempdir().unwrap();
    let root = root.path().canonicalize().unwrap();
    std::fs::write(root.join("tsconfig.json"), "{\"include\":[\"**/*\"]}").unwrap();
    let source = "<script setup>const label = 'before';</script><template>{{ label }}</template>";
    let a = root.join("A.vue");
    let b = root.join("B.vue");
    for path in [&a, &b] {
        std::fs::write(path, source).unwrap();
    }
    let session = EditorMirrorSession::new();
    let overlays = FxHashMap::default();
    let first = open(&session, &a, source, &overlays);
    let sibling = open(&session, &b, source, &overlays);
    let a_request = request(&first, &a);
    let b_request = request(&sibling, &b);
    let changed = source.replace("before", "a longer 🦀 authored prefix");
    let edited = open(&session, &b, &changed, &overlays);
    assert!(
        !edited
            .source_catalog
            .shares_revision_with(&first.source_catalog)
    );
    assert_eq!(
        first
            .source_catalog
            .get(&b_request)
            .unwrap()
            .source
            .as_str(),
        source
    );
    let new_b = edited.source_catalog.get(&b_request).unwrap();
    assert_eq!(new_b.source.as_str(), changed);
    mapped_label(&new_b);
    assert!(std::sync::Arc::ptr_eq(
        &first.source_catalog.get(&a_request).unwrap(),
        &edited.source_catalog.get(&a_request).unwrap(),
    ));
}
